[[introduction]]
== Introduction

Looking Glass is a tracer and profiler for Erlang/OTP.

Looking Glass is the next generation profiling tool. It
is implemented as an `erl_tracer` NIF and thus requires
Erlang/OTP 19.0 or above.

Looking Glass aims to provide a very efficient tool
usable both in development and production settings,
and capable of running for a very long amount of time
even on busy systems.

=== Supported platforms

Looking Glass is currently developed on Linux but should
also work on OSX and Windows.

Looking Glass requires Erlang/OTP 19.0 or above.

A cachegrind tool is required for reading the output
from `lg_callgrind`. The `qcachegrind` tool (also
known as `kcachegrind`) is recommended. Note that
it is a good idea to also install `graphviz` to
have the quite informative call graphs.

=== Requirements

Looking Glass requires the LZ4 library to be installed.
Installation instructions depend on your system.

On Arch Linux:

[source,bash]
$ pacman install lz4

On OSX with Homebrew:

[source,bash]
$ brew install lz4

=== License

Looking Glass is double-licensed under the Mozilla
Public License 1.1 and the Apache License version 2.

See the LICENSE file for more information.

=== Versioning

Looking Glass uses http://semver.org/[Semantic Versioning 2.0.0].
