name: CI

on: [push, pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [22.3, 23.3, 24.1]
    container:
      image: erlang:${{ matrix.otp }}-alpine
    steps:
    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash curl bsd-compat-headers
    - uses: actions/checkout@v2
    - name: Build
      run: rebar3 compile
    - name: Run tests
      run: |
           rebar3 ct
           make ct
